//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AproveitamentoDeNotas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_aproveitamentoEntities : DbContext
    {
        public db_aproveitamentoEntities()
            : base("name=db_aproveitamentoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_aproveitamento> tb_aproveitamento { get; set; }
        public virtual DbSet<tb_curso> tb_curso { get; set; }
        public virtual DbSet<tb_disciplina> tb_disciplina { get; set; }
        public virtual DbSet<tb_funcao_usuario> tb_funcao_usuario { get; set; }
        public virtual DbSet<tb_instituto> tb_instituto { get; set; }
        public virtual DbSet<tb_situacao_aprov> tb_situacao_aprov { get; set; }
        public virtual DbSet<tb_usuarios> tb_usuarios { get; set; }
    }
}
