//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AproveitamentoDeNotas
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_disciplina
    {
        public int id_disciplina { get; set; }
        public string nome_disciplina { get; set; }
        public int carga_horaria { get; set; }
        public string ano_semestre { get; set; }
        public string descricao { get; set; }
        public int id_curso { get; set; }
        public int id_instituto { get; set; }
    
        public virtual tb_curso tb_curso { get; set; }
        public virtual tb_instituto tb_instituto { get; set; }
    }
}
