//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AproveitamentoDeNotas
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_funcao_usuario
    {
        public tb_funcao_usuario()
        {
            this.tb_usuarios = new HashSet<tb_usuarios>();
        }
    
        public int id_funcao_usuario { get; set; }
        public string funcao { get; set; }
    
        public virtual ICollection<tb_usuarios> tb_usuarios { get; set; }
    }
}
