//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AproveitamentoDeNotas
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_situacao_aprov
    {
        public tb_situacao_aprov()
        {
            this.tb_aproveitamento = new HashSet<tb_aproveitamento>();
        }
    
        public byte id_situacao_aprov { get; set; }
        public string nome_situacao_aprov { get; set; }
    
        public virtual ICollection<tb_aproveitamento> tb_aproveitamento { get; set; }
    }
}
