//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AproveitamentoDeNotas
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuarios
    {
        public int id_user { get; set; }
        public string nome_user { get; set; }
        public string pass_user { get; set; }
        public Nullable<int> id_funcao_usuario { get; set; }
    
        public virtual tb_funcao_usuario tb_funcao_usuario { get; set; }
    }
}
